import { execFileSync } from "node:child_process";
import { readFile, mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { format } from "prettier";

const rootDirectory = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = resolve(
  rootDirectory,
  "src/shared/api/supabase/database.types.ts",
);
const checkOnly = process.argv.includes("--check");

const generatedTypes = execFileSync(
  "pnpm",
  [
    "exec",
    "supabase",
    "gen",
    "types",
    "typescript",
    "--local",
    "--schema",
    "public",
  ],
  {
    cwd: rootDirectory,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "inherit"],
  },
);

const formattedTypes = await format(
  `// Generated by \`pnpm db:types\`. Do not edit manually.\n\n${generatedTypes}`,
  { parser: "typescript" },
);

if (checkOnly) {
  const currentTypes = await readFile(outputPath, "utf8").catch(() => "");

  if (currentTypes !== formattedTypes) {
    console.error(
      "Database types are stale. Run `pnpm db:types` and commit the result.",
    );
    process.exitCode = 1;
  } else {
    console.log("Database types are up to date.");
  }
} else {
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, formattedTypes);
  console.log(`Generated ${outputPath}`);
}
